# Generated by Django 5.0.6 on 2024-07-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amt',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
