# Generated by Django 5.0.6 on 2024-08-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0010_remove_cart_address_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='address',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
