# Generated by Django 5.0.6 on 2024-08-02 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0011_cart_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
