# Generated by Django 5.0.6 on 2024-08-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0012_remove_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
