# Generated by Django 5.0.6 on 2024-08-02 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0013_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
